pipeline {
    agent any
    stages {  
        stage ("build") {
            
            steps {
               echo 'Building anotherJob and getting the log'
            }
        }          
   }}