pipeline {
    agent any

    stages {  
        stage ("build") {
            tools {
               jdk "jdk 8"
               
            }
            steps {
                sh 'java -version'
            }
        }          
   }}